---
# tasks file for dblb

- name: "Configure DB HAProxy instance with templated configuration"
  become: true
  template:
        src: "db-haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
        owner: "root"
        group: "root"
        mode: 0644

- name: "Restart HAproxy"
  become: true
  command: ./restart_haproxy.sh
