---
# tasks file for web

- name: "Copy the Nginx configuration file "
  become: true
  template:
      src: "web-nginx.cfg.j2"
      dest: "/etc/nginx/nginx.conf"
      owner: "root"
      group: "root"
      mode: 0644

- name: "Restart nginx"
  service:
         name: nginx
         state: restarted
  become: yes
